// Every entity in the system will inherit from this base entity class. 
// It contains common properties that all entities should have, such as global unique identifier (GUID), CreatedAt, and UpdatedAt.
using DevBoard.Domain.Entities;
namespace DevBoard.Domain.Entities
{
    // The BaseEntity class serves as a base class for all entities in the system. 
    // It provides common properties that are shared across different entities on this DevBoard App.
    public abstract class BaseEntity
    {
        // Autogenerated global unique identifier for the entity. This property is initialized with a new GUID when the entity is created.
        public Guid Id { get; init; }= Guid.NewGuid();

        // Timestamp indicating when the entity was created.
        public DateTime CreatedAt { get; init; } = DateTime.UtcNow;

        // Timestamp indicating when the entity was last updated.
        public DateTime? UpdatedAt{get; set;}

       
    
    }
}